/**
 * Writes the static HTML for every route × shipped locale, plus the sitemap and
 * the 404 page.
 *
 * Output uses the directory-index form (`/compress-image-to-size/index.html`)
 * because it is the one convention every static host serves identically —
 * Cloudflare Pages, GitHub Pages, S3 and nginx all resolve `/foo` to
 * `foo/index.html`. Canonical URLs are emitted WITHOUT a trailing slash, and the
 * host is left to serve them; one canonical form, no redirect chains.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { LOCALES, DEFAULT_LOCALE, type LocaleCode } from '../i18n/locales';
import { allPaths, alternatesFor, urlFor, pathFor, ROUTES, SITE, type RouteKey } from '../i18n/routes';
import { MESSAGES, SHIPPED_LOCALES, messagesFor } from '../i18n/all-messages';
import { buildHead, htmlAttrs, esc } from './head';
import { buildBody } from './body';

const SEO_BLOCK = /<!--seo:start-->[\s\S]*?<!--seo:end-->/;
const BODY_SLOT = '<!--app:body-->';
const HTML_TAG = /<html\b[^>]*>/;

/** Splice a generated head and body into the built template. */
export function composePage(
  template: string,
  opts: { key: RouteKey | 'not-found'; locale: LocaleCode; noindex?: boolean },
): string {
  const messages = messagesFor(opts.locale);
  const headKey: RouteKey = opts.key === 'not-found' ? 'home' : opts.key;

  const head = buildHead({
    key: headKey,
    locale: opts.locale,
    messages,
    noindex: opts.noindex ?? opts.key === 'not-found',
    locales: SHIPPED_LOCALES,
  });
  const body = buildBody({
    key: opts.key,
    locale: opts.locale,
    messages,
    locales: SHIPPED_LOCALES,
  });

  let out = template;
  if (!SEO_BLOCK.test(out)) throw new Error('index.html is missing the <!--seo:start--> block');
  if (!out.includes(BODY_SLOT)) throw new Error('index.html is missing the <!--app:body--> slot');

  out = out.replace(SEO_BLOCK, head);
  out = out.replace(BODY_SLOT, body);
  out = out.replace(HTML_TAG, `<html ${htmlAttrs(opts.locale)}>`);
  return out;
}

/** Where a URL path is written on disk. */
export function fileForPath(p: string): string {
  const clean = p.replace(/^\/+|\/+$/g, '');
  return clean ? path.join(clean, 'index.html') : 'index.html';
}

/**
 * A sitemap carrying xhtml:link alternates. Google reads the language cluster
 * from here as well as from the page head; having both agree is what stops it
 * picking one locale and dropping the rest.
 */
export function buildSitemap(lastmod: string): string {
  const rows = allPaths(SHIPPED_LOCALES)
    .map(({ key, locale }) => {
      const alts = alternatesFor(key, SHIPPED_LOCALES)
        .map(
          (a) =>
            `    <xhtml:link rel="alternate" hreflang="${esc(a.hreflang)}" href="${esc(a.href)}" />`,
        )
        .join('\n');
      const priority = key === 'home' ? '1.0' : ROUTES[key].localized ? '0.9' : '0.3';
      const freq = key === 'privacy' ? 'yearly' : key === 'home' ? 'weekly' : 'monthly';
      return [
        '  <url>',
        `    <loc>${esc(urlFor(key, locale))}</loc>`,
        `    <lastmod>${lastmod}</lastmod>`,
        `    <changefreq>${freq}</changefreq>`,
        `    <priority>${priority}</priority>`,
        alts,
        '  </url>',
      ]
        .filter(Boolean)
        .join('\n');
    })
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${rows}
</urlset>
`;
}

/**
 * Cloudflare Pages `_headers`.
 *
 * Generated rather than hand-written because the isolated video route now has a
 * different URL in every locale: a hand-maintained list would silently stop
 * matching the day a slug changed, and the failure — losing SharedArrayBuffer,
 * so ffmpeg drops to single-threaded — is invisible until someone times a
 * compression.
 */
export function buildHeaders(): string {
  const videoRoutes = SHIPPED_LOCALES.map((l) => pathFor('video-compress', l.code));
  const isolated = videoRoutes
    .map(
      (p) =>
        `${p}\n  Cross-Origin-Opener-Policy: same-origin\n  Cross-Origin-Embedder-Policy: require-corp`,
    )
    .join('\n');

  return `# GENERATED by scripts/prerender.mjs. Edit src/prerender/render.ts, not this file.
#
# COOP/COEP (cross-origin isolation) unlocks SharedArrayBuffer for multithreaded
# ffmpeg.wasm, but it breaks AdSense. So isolate ONLY the video-processing
# route and keep it ad-free; every other route stays unisolated and monetized.
# Validated locally: see spike/coop-coep/FINDINGS.md (docs/10 item 2).
# Fallback: single-threaded ffmpeg.wasm, which removes the conflict.
${isolated}

# Hashed assets: long cache. CORP+COEP so the isolated route can embed them:
# the ffmpeg WORKER script and .wasm binary need BOTH (a dedicated worker in an
# isolated page must itself be require-corp; the spike proved CORP alone fails).
# Harmless on unisolated routes.
/assets/*
  Cache-Control: public, max-age=31536000, immutable
  Cross-Origin-Resource-Policy: same-origin
  Cross-Origin-Embedder-Policy: require-corp

# Prerendered HTML is NOT content-hashed; its URL is the page's URL. Caching it
# like an asset would pin visitors to a stale copy of the page, and a stale
# canonical, until the CDN expired it. Revalidate every time; these responses are
# a few KB and 304s cost nothing.
/*
  Cache-Control: public, max-age=0, must-revalidate
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin

/sitemap.xml
  Cache-Control: public, max-age=3600
/robots.txt
  Cache-Control: public, max-age=3600
`;
}

export function buildRobots(): string {
  return `User-agent: *
Allow: /

# The 404 page is noindex, but keep crawlers out of it entirely.
Disallow: /404.html

Sitemap: ${SITE}/sitemap.xml
`;
}

export interface RenderReport {
  pages: number;
  locales: LocaleCode[];
  missing: LocaleCode[];
}

/** Generate everything into `dist`. Returns a report for the build log. */
export async function renderAll(dist: string, lastmod: string): Promise<RenderReport> {
  const templatePath = path.join(dist, 'index.html');
  const template = await readFile(templatePath, 'utf8');

  const targets = allPaths(SHIPPED_LOCALES);
  for (const { key, locale, path: urlPath } of targets) {
    const html = composePage(template, { key, locale });
    const file = path.join(dist, fileForPath(urlPath));
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, html, 'utf8');
  }

  // 404: real status comes from the host serving /404.html; the noindex meta is
  // what stops a soft-404 from being indexed if it is ever reached directly.
  await writeFile(
    path.join(dist, '404.html'),
    composePage(template, { key: 'not-found', locale: DEFAULT_LOCALE, noindex: true }),
    'utf8',
  );

  await writeFile(path.join(dist, 'sitemap.xml'), buildSitemap(lastmod), 'utf8');
  await writeFile(path.join(dist, 'robots.txt'), buildRobots(), 'utf8');
  await writeFile(path.join(dist, '_headers'), buildHeaders(), 'utf8');

  return {
    pages: targets.length + 1,
    locales: SHIPPED_LOCALES.map((l) => l.code),
    // Declared in the locale table but not yet translated. Reported so a
    // half-finished locale is visible in the build log rather than silently
    // absent from the sitemap.
    missing: LOCALES.filter((l) => !MESSAGES[l.code]).map((l) => l.code),
  };
}
