/**
 * The per-tool technical article.
 *
 * docs/06 calls this "the differentiating asset": the thing that separates a
 * thin tool page from one that earns links. A bare upload-process-download page
 * is what Google's publisher policies prohibit ads on, and a paragraph of
 * marketing does not fix that. These explain the mechanism.
 *
 * ENGLISH ONLY, and rendered only on the English pages. Long-form technical
 * writing is the worst possible candidate for machine translation: the value is
 * entirely in precision, and a translated approximation of a precise claim is
 * just a wrong claim. The same reasoning keeps ../content/terms and
 * ../content/privacy to one language.
 *
 * Held as data, like the legal pages, so the route and the prerenderer render
 * one source and cannot drift.
 *
 * WRITE THEM ABOUT WHAT THE CODE ACTUALLY DOES. Every article below describes
 * this implementation, not the general topic: the search loop in
 * core/target-size, the rejection sampling in core/words, the DOMException
 * names in core/media. That is the part a reader cannot get from a competitor,
 * and it is what makes the page worth linking to.
 */
import type { ToolKey } from '../i18n/routes';

export interface ToolArticle {
  heading: string;
  paragraphs: string[];
}

export const ARTICLES: Partial<Record<ToolKey, ToolArticle>> = {
  'pdf-password': {
    heading: 'The two passwords on a PDF, and why this tool only sets one',
    paragraphs: [
      'A PDF can carry two passwords, and almost every problem people have with protected PDFs comes from not knowing that. The user password is the one that decrypts the document: without it there is nothing to display, because the content streams are ciphertext. The owner password governs permissions (printing, copying, annotating) and a file can carry an owner password while having no user password at all. Such a file opens for anybody who double-clicks it, shows every word, and still reports itself as "password protected" in every summary that bothers to look. This tool sets the same string as both, so the only meaning a password has here is the one people expect: the file needs it to open.',
      'That distinction matters more than it sounds, because the permissions half is not enforced by cryptography. The flags that say "do not print" are stored in the encryption dictionary, and honouring them is a request to the reader software. The specification says a conforming reader should obey them; nothing stops one that does not, and the flags are readable without any password when only an owner password is set. Any tool that offers to "restrict printing" without encrypting is offering a preference, not a protection, and this one does not offer it.',
      'The encryption is AES-256, which in PDF terms means a security handler of revision 6: `/V 5 /R 6 /AESV3` in the encryption dictionary, which you can see in the output with any hex viewer. The alternative the format still permits is RC4 at 40 or 128 bits, and qpdf, which does the work here, refuses to write those without an explicit `--allow-weak-crypto`. That flag is never passed. Asking for `--bits=128` therefore fails outright rather than quietly producing a weaker file, which is the correct behaviour and the reason there is no key-length control in the interface: there is one defensible answer, and presenting it as a choice would only invite a worse one.',
      'The password itself is capped at 127 bytes, and the tool rejects anything longer instead of accepting it. This is not an arbitrary limit, because the standard truncates at that length, so a longer password would be silently cut down, and the file would then open with a prefix of what was typed rather than the whole thing. A user who pasted a 200-character passphrase would have a file that refuses the passphrase they think protects it. The limit is measured in bytes rather than characters, which matters as soon as the password contains anything outside ASCII: an emoji is four bytes, so thirty-two of them are already over.',
      'None of the cryptography is ours. qpdf is compiled to WebAssembly and runs inside the page, which is a deliberate choice rather than a convenience: implementing PDF encryption by hand would mean writing cryptographic code for a security feature, and the fact that the algorithm is fully specified does not make that a reasonable thing to do. The trade-off is that qpdf’s only WebAssembly build imports shared memory, so the page has to be cross-origin isolated to run it at all. That is why this route is served with COOP and COEP headers and carries no advertising: the isolation that makes threads available is the same isolation that blocks third-party scripts.',
      'Everything happens on the device, which has a consequence worth stating plainly rather than burying. The password is never transmitted and never stored, so there is no reset, no recovery address and no copy anywhere. A forgotten password means the file is gone, and that is not a limitation of this implementation; it is what encryption is. The same property that makes it safe to protect a document here makes it impossible to rescue one.',
    ],
  },
  'sheet-convert': {
    heading: 'Three bytes, a leading zero, and the spreadsheet that runs code',
    paragraphs: [
      'Converting a CSV to a spreadsheet is one library call in any language you like. That is exactly why the internet has a thousand converters and why most of them are subtly wrong: the call is the easy part, and everything that decides whether the output is usable happens after it, on a machine the author never sees.',
      'Start with the encoding, because it is the one everybody hits. Excel on Windows does not assume UTF-8. Handed a CSV with no byte order mark it falls back to the system ANSI code page, and every character above ASCII is reinterpreted: café becomes cafÃ©, Müller becomes MÃ¼ller, and a customer list arrives looking corrupted. The fix is three bytes, EF BB BF, at the front of the file. It has been the fix for twenty years. It is still missing from most exports, and it is why so many teams believe "Excel cannot handle UTF-8" when what Excel cannot handle is being left to guess.',
      'The second problem is worse, because it destroys data rather than displaying it wrongly. CSV has no types: every value is text, and Excel decides on import what each one means. A postcode of 01234 is read as the number 1234 and the zero is gone. A sixteen-digit order number exceeds what a double can hold exactly, so it becomes 1.23457E+15 and the last digits are not hidden but lost. A product code of SEPT1 becomes a date. That last one was severe enough in genetics that human gene names were officially renamed in 2020 because researchers could not stop Excel corrupting them, which is a remarkable sentence to have to write about a spreadsheet.',
      'This is the real argument for converting to a genuine .xlsx instead of renaming a CSV and hoping. An .xlsx records the type of every cell, so a value written as text stays text no matter what it looks like. The conversion has to be deliberate about it: mark too much as text and real numbers stop being numbers, breaking every formula downstream, so the rule has to be narrow. Leading zeros, integers too long for a double, and the short codes that look like dates. Everything else is left alone.',
      'The third is not correctness but safety. A cell beginning with =, +, - or @ is a formula, and a spreadsheet assembled from data somebody else supplied is a way to run their code on the machine that opens it. The temptation is to sanitise silently by prefixing an apostrophe. The better answer is to count them and say so, because a tool that quietly edits the contents of your data has made a decision that was not its to make. Report, and let the person who understands the data choose.',
    ],
  },
  'batch-rename': {
    heading: 'The two rules a bulk renamer has to get right, and usually does not',
    paragraphs: [
      'Bulk renaming looks like string formatting. Take a prefix, take a counter, join them, done. The trouble is that a file name is not a string: it is a string that has to survive three operating systems, a ZIP archive and a file manager that sorts it, and each of those has an opinion. Two of those opinions are where almost every quick renaming script fails.',
      'The first is sorting. File managers sort names as text, and as text, "photo-10" comes before "photo-2", because the character 1 sorts before 2 and the comparison stops there. A person renaming a hundred holiday photos in sequence discovers this at photo-10 and finds their carefully ordered set jumbled. The fix is to pad every number to the width of the largest, so ten files are 01 to 10 and a hundred are 001 to 100. It is one line, it must be derived from the size of the batch rather than fixed at two digits, and it is the single most common reason people give up on a renaming script and do it by hand.',
      'The second is what a name is allowed to contain. Unix will accept almost anything except a slash and a null byte, which makes it a poor teacher: a name that works perfectly on the machine that made it can be impossible to write on Windows. Windows forbids nine characters outright, silently truncates a name that ends in a dot or a space, and still, in 2026, refuses to create a file called CON, PRN, AUX, NUL, COM1 or LPT1, with or without an extension, because those were device names in DOS and the compatibility was never broken. A renamer that does not know this produces an archive that unpacks fine for its author and fails for the person they send it to.',
      'Then there is the case nobody plans for: two files that want the same name. It happens more often than it sounds. A burst of photos shares a capture second, so naming by timestamp collides. Two names that differed only in punctuation tidy down to the same thing. And the failure is quiet in the worst way, because a ZIP is perfectly happy to contain two entries with identical names; what happens on extraction is up to the unpacker, and the usual answer is that one photo silently overwrites the other. The only safe design is to track every name already issued and number the duplicates, comparing case-insensitively because Windows and macOS both consider A.jpg and a.jpg the same file.',
      'None of this is difficult. All of it is invisible when it is right, and all of it produces a bug report weeks later when it is wrong, from someone who cannot open the files you sent them.',
    ],
  },
  'color-picker': {
    heading: 'Why palette extractors return colours that are not in the picture',
    paragraphs: [
      'Feed a photograph of a red flower on green leaves into most palette tools and somewhere in the results will be a brown that appears nowhere in the image. It is not a bug in the sense of a mistake in the code. It is the textbook algorithm doing exactly what it says, and the fault is in a single step that looks harmless.',
      'The algorithm is median cut. Put every pixel in one box in colour space, find the axis the box is most spread along, split it at the median, and repeat on whichever box is now the most spread out until there are as many boxes as you want colours. It is fast, it needs no tuning, and it divides an image sensibly. Then comes the step that ruins it: take the average of each box and call that the swatch. The average of a red pixel and a green pixel is brown, and if a box straddles the flower and the leaf, brown is what you get. The palette is arithmetically correct and visually a lie.',
      'The fix costs one pass. Instead of the average, take the real pixel nearest to it. The box still says which region of colour space matters; the pixel makes sure the answer is a colour someone could have pointed at. Everything offered is then defensible, because it is in the picture.',
      'A second, quieter error hides in what these tools report as a percentage. Median cut splits at the median, which means every box holds roughly the same number of pixels by construction. Reporting box population as a share therefore says all six colours cover about a sixth of the image each, no matter what the image looks like, and a photograph that is three-quarters sky will be described as evenly balanced. The shares have to be measured after the fact, by asking of every pixel which swatch it is nearest to. Only then does the sky come back as three-quarters.',
      'The last thing worth mentioning is the one-pixel read. Draw an image into a canvas and read a pixel back with smoothing left on, which is the default, and the browser hands you a blend of that pixel and its neighbours. The colour is plausible, close to right, and does not match the source when you paste it into a stylesheet and compare. Turning smoothing off for that read is a single line, and it is the difference between an eyedropper and something that approximately agrees with one.',
    ],
  },
  'screenshot-split': {
    heading: 'Where to cut a long screenshot, and why the obvious answer is wrong',
    paragraphs: [
      'Splitting an image into pieces is arithmetic that a beginner can write: take the height, divide by the number of parts, cut there. It works perfectly and produces a bad result, because the one thing the arithmetic cannot know is that row 4,000 happens to run straight through the middle of a line of text. Half a sentence at the bottom of one image and half at the top of the next is the signature of a split done this way, and it is the reason people go back to doing it by hand in an image editor.',
      'The fix is to stop treating a cut as a position and start treating it as a preference. The even division says where the cut would ideally go; the picture gets a say in where it actually goes. Allow each cut to move by around a line and a half, and there is almost always somewhere better within reach, because text is not continuous. It comes in lines with gaps between them, in bubbles with padding around them, in sections with rules between them. A capture that looks dense is mostly empty rows.',
      'Finding them needs a measure of how busy a row is, and the cheapest useful one is counting transitions: walk the row and count how often the colour changes by more than a hair. A row crossing text changes at every character edge and scores in the hundreds. A row in the gap between paragraphs scores zero. This is not edge detection, and deliberately so: it runs on a phone over tens of thousands of rows, and one comparison per pixel with no arithmetic is what keeps it instant.',
      'Two rules keep the nudging honest. A cut only moves somewhere strictly quieter than where it already is, so a photograph or a gradient, which has no quiet rows anywhere, keeps its even division instead of being pushed around by noise. And among equally quiet rows the nearest wins, because a run of thirty blank rows would otherwise always snap to its first one and drag the cut further than it needed to go.',
      'The last decision is about memory, and it is the one that separates a demo from a tool. Scoring every row means reading every pixel, and a 1,000 by 20,000 capture is 80 MB of RGBA, which is enough to end the tab on a phone, and a phone is exactly the device the capture came from. But a cut can only move as far as its radius, so all but a few hundred of those rows were never candidates. Reading one narrow band around each cut costs a fraction of a megabyte and answers precisely the same question. The general lesson is worth keeping: when an algorithm looks too expensive, check whether it is being asked about data whose answer could never have mattered.',
    ],
  },
  'image-crop': {
    heading: 'A fraction is not a shape, and that is why your square crops are not square',
    paragraphs: [
      'Any crop tool that works on a preview has the same problem to solve. The image on screen is a few hundred pixels wide; the original might be four thousand. The selection has to be recorded in a way that survives that gap, and the obvious answer is to store it as a proportion of the image: this box starts 20 percent across and is 40 percent wide. Scale-independent, resolution-independent, and correct.',
      'It is correct right up until a ratio is involved. Take a 2000 by 1000 photo and a selection half the width and half the height. In fractions that is a perfect 0.5 by 0.5, which looks square written down. In pixels it is 1000 by 500, which is 2:1. The fractions are equal and the shape is not, because the axes have different lengths underneath them. A tool that constrains ratios in fraction space produces crops that are square in the numbers and visibly wrong on the screen, and the error grows with how far from square the original was.',
      'So the constraint has to be applied in pixels. Convert the fractional selection to pixels using the image dimensions, adjust the width or height there to hit the target ratio, convert back. The step is small and easy to skip, and skipping it is why so many crop tools produce a 1080 by 1074 square that an upload check rejects for not being square.',
      'Then there is the question of which way to adjust. A selection that is too wide for the target ratio can be fixed by narrowing it or by making it taller, and the second is a trap: the user drew that box, and growing it means growing past whatever edge they drew near. Shrinking the over-long side always stays inside the image, always keeps the region the user was looking at, and never surprises them by expanding into content they deliberately excluded. Recentring on the original midpoint keeps the subject where they put it.',
      'The last piece is what cropping does to quality, which is nothing. Unlike resizing, a crop copies pixels one for one; there is no resampling, no interpolation, no softening. The only loss is the re-encode, and that is a choice of format rather than a consequence of cropping. This is worth knowing because it makes the order of operations matter: crop first and resize second, and you resample once. Do it the other way and you resample the whole picture in order to throw most of it away.',
    ],
  },
  'image-resize': {
    heading: 'Three ways to fit a rectangle in a square, and only two of them are honest',
    paragraphs: [
      'The request sounds simple and contains a contradiction. Make this photo 1080 by 1080. The photo is 4032 by 3024, which is 4:3, and no amount of arithmetic turns a 4:3 rectangle into a 1:1 square while keeping every pixel in proportion. Something has to give: either part of the picture leaves the frame, or the frame gains ground the picture does not cover, or the picture is distorted to fill it. Every image resizer answers this question. Most do not tell you which answer they picked.',
      'Stretching is the answer nobody asks for and many tools default to, because it is the one that needs no decision: scale x and y independently until the numbers match. The result is a face 33 percent too wide, and the striking thing is how reliably people notice something is wrong without being able to say what. Faces in particular are processed by dedicated machinery in the visual system that is exquisitely sensitive to proportion, which is why a stretched portrait reads as uncanny while a stretched landscape merely reads as slightly odd.',
      'Cropping to fill is what social platforms do. Scale by the larger of the two ratios so the box is covered, then trim the overflow. The subject stays in proportion and the edges are lost, which is fine for a profile picture where the face is in the middle and wrong for a group photo where someone is standing at the edge. Centring the crop is the only defensible default, since the tool has no idea what the subject is, and saying so plainly is better than pretending the choice was intelligent.',
      'Fitting inside does the opposite: scale by the smaller ratio so the whole picture survives, then fill the remainder with a background. Nothing is lost and the result has bands along two sides. This is what a fixed frame wants, and what a printer expects when the paper is not the aspect ratio of the photograph. The bands are only invisible when the background matches whatever the image will sit on, which is why the colour matters more than it looks like it should.',
      'Rounding deserves a mention because it is where exactness quietly fails. Scale factors are rarely whole numbers, so the computed draw size lands at 249.6 pixels and something has to decide what that means. Rounding the drawn image is fine; rounding the CANVAS is not, because a canvas of 1079 pixels when 1080 was requested breaks the one promise the tool makes. The canvas is therefore set to the requested integers first and the drawing is fitted into it, rather than the other way around. The same applies at the small end: a one-pixel target is legal, and a plan that rounds a dimension to zero would produce a blank image instead of a tiny one.',
    ],
  },
  'sheet-clean': {
    heading: 'Why your duplicate rows survive every attempt to remove them',
    paragraphs: [
      'Two rows that look identical on screen are frequently not identical to a computer, and the reasons are almost always invisible. The commonest is a trailing space, picked up when a value was pasted from a web page or exported from a system that padded its fields. "Ana" and "Ana " differ by one byte, so any comparison treats them as distinct, the duplicate check finds nothing, and the row you can plainly see twice stays twice.',
      'There are subtler versions. A non-breaking space, U+00A0, is what you get when text comes from HTML, and it looks exactly like a space while comparing unequal to one. Numbers stored as text compare unequal to the same numbers stored as numbers, which is why a column of ids can fail to match itself after a round trip through CSV. Unicode makes it worse: an accented character can be a single code point or a base letter followed by a combining accent, identical on screen and different in memory, which is what normalisation forms exist to reconcile.',
      'The order of operations therefore matters more than the operations. Trimming has to happen before deduplication, not after, or the padded row survives the comparison as a distinct value and gets removed only from the tidied output, leaving the duplicate behind. Blank-row removal has to come before deduplication too, otherwise several blank rows are themselves duplicates of each other and the count of what was removed becomes confusing to read. This tool runs trim, then blank-row removal, then deduplication, and reports each separately so the numbers add up.',
      'What counts as a duplicate is a decision, not a fact. Matching on every column is the strict reading and the safe default: two rows are the same row only if they agree everywhere. Matching on a key column instead, so that a later record supersedes an earlier one, is a different job with different risks, and it is the one the spreadsheet comparison tool is for. Conflating them in a single button is how people delete rows they meant to keep.',
      'The masking half of the tool has its own subtlety worth stating. Replacing a value with one bullet per character preserves its length, and length is information: a masked phone number of ten characters beside one of nine tells a reader something about both. A fixed-width mask gives that away nothing, at the cost of the column no longer showing which entries were longer, which is a trade worth making by default. Removing the column outright gives away less still, and is the right choice whenever the recipient has no reason to know the column ever existed.',
    ],
  },
  redact: {
    heading: 'The black rectangle that is only a drawing',
    paragraphs: [
      'In 2011 a court filing about a well known technology dispute was published with sections blacked out, and within hours people had the text: the blocks were rectangles drawn over a page whose words were still underneath, and selecting the region and pasting it revealed everything. The same mistake has been made since by government departments, law firms and newspapers, and it will be made again next month. It is not a rare accident. It is the default outcome of the most obvious way to do the job.',
      'The reason is structural. A PDF is a collection of objects: text-showing operators with their fonts and positions, images, vector paths. Drawing a filled rectangle adds one more object to that collection, on top in painting order. It changes what a viewer displays and nothing about what the file contains. The text operators are untouched, so text extraction returns them, copy and paste returns them, a screen reader reads them aloud, and any of a hundred libraries can list them in a line of code. The document looks redacted to a human and is not redacted at all to a program.',
      'Genuine redaction has to remove the objects, and there are two ways. The precise one is surgical: parse the content stream, find the text-showing operators whose glyph positions fall inside the region, and rewrite the stream without them. It preserves the rest of the page as real text and it is genuinely difficult, because glyphs are positioned by a running matrix that later operators depend on, fonts may be subset so removing the last use of a glyph can invalidate the font, and a partially covered word has to be split rather than dropped.',
      'The blunt one is to rasterise. Render the page to pixels at a sensible resolution, paint the boxes onto those pixels, and build a new document with the result as an image. Every text object in the original is gone, not because it was carefully removed but because nothing from the original structure survived the trip through a bitmap. There is no content stream left to mine. This is what the tool does, and the honesty of it is the point: it is impossible to get subtly wrong, which is exactly the failure mode the surgical approach has.',
      'The trade is real and worth stating plainly. The output cannot be searched, selected or read aloud, and it is larger. A redaction you can still search is a redaction that still contains the text, so those two properties cannot both be had for the same words. What you can have is a document where the words that mattered are unrecoverable, which is the requirement people actually have when they reach for this. Rounding also matters more than it sounds: the boxes are rounded outward to whole pixels, because a box that rounds inward can leave a one pixel line of the original along its edge, and a redaction that leaks a sliver of what it hid is worse than none, since it looks finished.',
    ],
  },
  'pdf-to-images': {
    heading: 'Why a PDF page has no resolution until you ask for one',
    paragraphs: [
      'A JPEG knows how big it is. Somewhere in its header sit two numbers, a width and a height in pixels, and every pixel is stored explicitly. A PDF page has neither. What it has is a MediaBox giving its size in points, where a point is exactly 1/72 of an inch by definition, and a content stream of drawing operators: move here, set this font, show this string, fill this path. Nothing in there is a pixel. The page is a set of instructions for producing an image, not an image.',
      'That is why the question "what resolution is this PDF?" has no answer, and why converting one to a picture is a decision rather than a lookup. You are choosing how finely to execute those instructions. At 150 dots per inch an A4 page becomes about 1240 by 1754 pixels; at 300 it becomes 2480 by 3508, four times the pixels and roughly four times the work. The text is drawn from font outlines at whichever size you picked, so it comes out genuinely sharp at both, unlike an upscale of a small render, which cannot invent detail that was never computed.',
      'Rendering itself is done by pdf.js, Mozilla\'s PDF implementation compiled for the browser, which is the same engine Firefox uses to display PDFs. It runs in a worker thread, which matters more than it sounds: rasterising twenty pages is enough work to freeze a tab, and a frozen tab is indistinguishable from a broken one. The pages come back as canvases, and each is encoded and then explicitly released before the next begins, so a two hundred page document costs one page of memory rather than two hundred.',
      'One detail decides whether the output looks right or looks broken. A PDF page usually declares no background at all, on the reasonable assumption that it will end up on white paper. A canvas starts out transparent, and JPEG has no alpha channel, so transparent pixels are written as black. Convert without painting the canvas white first and every page comes back as white text on a black rectangle. It is a one-line fix and a completely convincing bug, because it looks like a rendering failure rather than a colour-space mistake.',
      'What you lose in the conversion is the thing that made the format worth having. Selectable, searchable, screen-readable text becomes a picture of text, and no amount of resolution brings it back. That is the right trade when something downstream simply will not accept a PDF, and the wrong one otherwise. If the words are what matter, the original file still has them, and OCR can recover them from the picture at some cost in accuracy.',
    ],
  },
  'pdf-split': {
    heading: 'A PDF is a bag of objects, which is why taking pages out costs nothing',
    paragraphs: [
      'Most file formats are a stream you read from the start. A PDF is not. It is a collection of numbered objects, and at the very end sits a cross-reference table saying which byte offset each object lives at. A page is one of those objects. It holds references to the fonts it uses, the images it draws, the text operators that place its glyphs, and a box giving its size. Nothing about a page says which document it belongs to or which page number it is, because that lives in a separate tree of nodes whose leaves point back at the pages.',
      'That structure is the reason splitting can be free. Extracting page seven means copying that object and everything it refers to into a new document, then building a one-leaf page tree that points at it. The glyph positions are untouched. The images are the same compressed streams they already were, at the same resolution. Nothing is decoded and nothing is re-encoded, so there is nothing to lose. Compare that with compressing to a hard size target, which eventually has no choice but to rasterise a page into a picture of itself and throw the text away.',
      'It also means the page size travels with the page rather than with the document. A file where page one is A4 and page two is US Letter is completely ordinary, and each page carries its own MediaBox to say so. A splitter that normalised everything to one size, or that assumed the first page spoke for the rest, would silently reflow scans that were fine. Copying the object keeps the box, so a mixed document stays mixed.',
      'Two things genuinely do not survive, and it is worth knowing why rather than being surprised later. Bookmarks are a separate outline tree with its own destinations, pointing at pages by reference; keep four pages out of forty and most of those destinations now point at nothing, so the outline is dropped rather than left broken. Form fields are the same story: the fields live in a document-wide AcroForm structure while only their widgets sit on the page, so an extracted page still shows the text that was typed into it, drawn exactly where it was, but there is no longer a field behind it to edit. The page looks identical and is no longer fillable.',
      'The last piece is the page list itself. It uses print-dialog notation because that is a notation people already have in their heads, and it turns out to express more than a print dialog uses it for. Order is meaningful, so 3,1,2 is a reordering rather than a selection. Repetition is meaningful, so 1,1 copies a page twice. Direction is meaningful, so 10-1 walks the range backwards and hands back a reversed document. One grammar covers extracting, deleting, reordering and reversing, which is why this tool has one text box instead of four modes.',
    ],
  },
  'image-convert': {
    heading: 'Why an iPhone photo is not a JPEG, and what renaming it does',
    paragraphs: [
      'Apple switched the default camera format to HEIC in 2017, and the reason was straightforward: it stores a photograph in roughly half the bytes of a JPEG at the same visual quality. HEIC is a container in the ISO base media family, the same family as MP4 video, holding an image compressed with HEVC. That inheritance is exactly the problem. HEVC is patent-encumbered, the licensing is awkward, and no browser ever shipped a decoder for it, so the format that half the phones in the world produce is the format the web cannot read.',
      'What people try first is renaming the file, and it is worth being precise about why that fails. The extension is metadata about a file, not part of it. Changing IMG_0042.HEIC to IMG_0042.jpg changes the label on the outside of the box and nothing inside it. Any program that opens the file reads its leading bytes, finds an ftyp box declaring the brand heic, and knows immediately that it is not the JPEG the name promises. The upload is refused, usually with a message that says nothing useful about which of the two facts was wrong.',
      'A real conversion has to decode the image into pixels and encode those pixels again in the new format. This tool decodes HEIC with libheif compiled to WebAssembly, which is downloaded the first time it is needed and then cached, and encodes through the canvas, which every browser implements. The image is drawn at its exact original dimensions, so nothing is scaled. One detail that gets handled explicitly: JPEG has no alpha channel, and an unpainted canvas is transparent black, so converting a transparent PNG to JPEG without filling the canvas first produces a picture with a black background rather than the white almost everyone expects.',
      'The other detail worth knowing is how support is decided. The canvas encoder takes a MIME type, and if it cannot write that type it does not throw or return null. It falls back to PNG and returns a blob whose type says image/png. A tool that offered every format and trusted the call would produce PNG bytes in a file named .avif, and the failure would surface much later, on somebody else’s machine. So the formats on offer here are probed at load: a one pixel canvas is encoded in each candidate format and the type of the result is checked against what was asked for. Only the ones that answered honestly appear.',
      'Because re-encoding starts from decoded pixels, EXIF does not survive it. The converted copy carries no GPS coordinate, no camera body, no timestamp from the original. That is a side effect rather than the purpose, but it is usually the one people want, and it is the reason converting is often a better answer than renaming even when renaming would have worked.',
    ],
  },
  'file-inspect': {
    heading: 'The first sixteen bytes are the only honest part of a file',
    paragraphs: [
      'A filename extension is a convention, not a property. Nothing enforces it. It survives being renamed, being copied, being emailed and being wrong, and the operating system will keep showing you a photo icon for a file that is not a photo. Every program that actually has to read the file ignores the name and looks at the bytes, which is why an upload can fail on a file your computer displays perfectly.',
      'Formats identify themselves in their first few bytes with a signature, usually called a magic number. A JPEG starts with FF D8 FF. A PNG starts with the byte 0x89 followed by the letters PNG and a short sequence chosen to detect damage in transfer. A PDF starts with the literal text %PDF-, and a ZIP with PK, the initials of Phil Katz, who wrote the original format in 1989. These are the first thing a decoder checks, and they are what this tool reads.',
      'Some families need a second look. The ISO base media container is used by MP4 video, by QuickTime, by AVIF images and by the HEIC photos an iPhone takes, and all of them begin with a length field followed by the letters ftyp. What separates them is the brand code immediately after: avif for an AVIF image, heic or mif1 for a HEIC photo, isom or mp42 for video. Reading only the ftyp box is how an inspector gets talked into calling a photograph a video. RIFF has the same shape, wrapping WebP, WAV and AVI behind identical opening bytes, with the payload type four bytes further in.',
      'Once the format is known, each one has its own place where information collects. JPEG and HEIC carry EXIF, a block written by the camera that can hold the GPS coordinates of the shutter press, the camera body and lens, and a name in the artist or copyright field. PDF has an information dictionary with the author, the producing software and two timestamps, and it survives edits to the text because nothing about editing text touches it. Office documents are ZIP archives, and a ZIP ends with a central directory that lists every part inside it, so the contents can be enumerated without decompressing a single byte or knowing any password. That listing is enough to see whether a document carries a vbaProject.bin, which is where a macro lives.',
      'All of this is a read, never a write. The bytes are examined in the tab and the file is left exactly as it was, which also means the tool can be pointed at anything without risk. If something turns up that should not travel with the file, the fix belongs to a different tool: strip the metadata, or convert the image to a format that never carried it in the first place.',
    ],
  },
  'image-compress': {
    heading: 'Why "quality 80" is not a file size',
    paragraphs: [
      'Every image compressor offers a quality slider, and the number on it tells you almost nothing about the file you will get. JPEG quality is not a ratio or a target. It selects a quantisation table, which decides how aggressively the encoder discards detail in each block of the image. How much smaller that makes the file depends entirely on what is in the picture.',
      'A photograph of a clear sky compresses enormously, because neighbouring pixels are nearly identical and the encoder can describe large areas cheaply. A photograph of gravel, foliage or a crowd does not, because there is genuine detail in every block and quantisation has less to throw away. The same quality 80 can produce a 90 KB file from one and a 900 KB file from the other. This is why "compress to quality 80" is a setting and "get this under 100 KB" is a job, and why asking a person to guess the first in order to achieve the second is a bad interface.',
      'So this tool does not ask. You state the size you need, and it searches for the quality that lands under it. Encode, measure the real byte count, adjust, repeat. It is a bisection over the quality axis: each attempt tells the search which half of the remaining range to keep, and a handful of encodes converges on the highest quality that still fits. The number of attempts is bounded, and the result is the actual encoded file rather than an estimate, because the only reliable way to know how big a JPEG is is to produce it.',
      'Two things fall out of that design. The first is that resolution is part of the answer. Below a certain size, no quality setting will fit a 12 megapixel photograph into 20 KB while leaving it recognisable, and the honest move is to reduce the dimensions rather than destroy the detail. The second is that the search runs on your device. Every one of those trial encodes happens in your browser, which is why the file never needs to be uploaded, and why the tool can afford to try repeatedly: nobody is paying for the CPU by the second.',
      'If you are choosing a format rather than a size: WebP typically lands 25 to 35 percent below JPEG at visually equivalent quality, and AVIF lower still, but both are slower to encode and JPEG remains the format that every government portal and recruitment site will definitely accept. When a form says "JPEG under 100 KB", it means it.',
    ],
  },

  'video-compress': {
    heading: 'Video size is bitrate multiplied by time, and nothing else',
    paragraphs: [
      'The arithmetic of video is simpler than people expect and it is the whole game. A video file is approximately its bitrate multiplied by its duration. Nine megabits per second for ten minutes is about 675 megabytes, and no amount of choosing "high quality" in a menu changes that relationship. If you need a two minute clip to fit under 16 MB for WhatsApp, you have roughly 1,000 kilobits per second to spend, and every decision after that is about how to spend them.',
      'This is why a quality slider on a video encoder is a worse interface than it is on an image encoder. With a still image you can encode, measure and retry in a fraction of a second. A video encode is minutes of work, so guessing a setting and discovering the result was 40 MB is expensive in a way that guessing at a JPEG is not. The size has to be planned before the encode, not discovered after it.',
      'So this tool works backwards from the target. It takes the duration, subtracts what the audio track needs, and derives the video bitrate that fits the remaining budget, then encodes once at that bitrate. The audio matters more than people expect at small targets: 128 kbps of stereo AAC over ten minutes is about 9.6 MB, which is most of a WhatsApp limit before a single frame of video is encoded. At aggressive targets, dropping the audio to mono at 64 kbps buys back more than any video setting will.',
      'Where the budget per second gets genuinely small, resolution has to come down too. Bitrate is spread across pixels, so 1,000 kbps looks acceptable at 640x360 and looks like a smear of blocks at 1920x1080. The encoder has the same number of bits either way; the question is whether it is describing two million pixels per frame or two hundred thousand. Reducing resolution is not giving up, it is spending the budget where it survives.',
      'The encoding runs in your browser through ffmpeg compiled to WebAssembly. That engine is about 30 MB, which is why it loads only when you actually compress something and never on the landing page. It is also why the video route is the one page on this site served with cross-origin isolation: threaded WebAssembly needs SharedArrayBuffer, and SharedArrayBuffer needs headers that would break ordinary advertising scripts, so that route gets them and no other route does.',
    ],
  },

  'pdf-compress': {
    heading: 'What is actually large inside a PDF',
    paragraphs: [
      'A PDF is a container, and the reason one is 40 MB is almost never the text. Text is stored as glyph references and font programs, and even a long document rarely spends more than a few hundred kilobytes on them. The size is in the images: scanned pages, photographs, screenshots and logos, each stored at whatever resolution it was placed at, which for a phone-scanned document is often far higher than anything the page can display.',
      'That leads to the single most useful distinction when shrinking a PDF, and the one most tools hide from you. Downsampling and recompressing the images inside a PDF keeps the document a document: the text stays text, remains selectable, remains searchable, and still works with a screen reader. Rasterising the pages, which is what "maximum compression" usually means, converts every page to a flat picture. The file gets much smaller and the text stops being text.',
      'The difference matters most in exactly the situations where people compress PDFs. A visa application, a tender submission or a court filing may be checked by software that reads the text. A rasterised page passes a size check and fails everything else, silently, and you find out later. So this tool downsamples images first and reports what it did, and if hitting your target genuinely requires rasterising, it says so before it does it rather than after.',
      'The other lever is what resolution the images need to be. A page destined for a screen or an ordinary office printer gains nothing from 600 dots per inch of scan data. 150 DPI is generally indistinguishable on screen, and often halves or quarters the file on its own. Where a scan is a photograph of a white page, converting it to greyscale removes two thirds of the colour data at essentially no cost to legibility.',
      'As with everything here, the work happens in your browser. That matters more for PDFs than for most formats, because the documents people need to compress are disproportionately the ones they should not be uploading: bank statements, medical records, identity documents, contracts under NDA.',
    ],
  },

  'image-to-pdf': {
    heading: 'What a PDF actually does with a photograph',
    paragraphs: [
      'A PDF page is a list of drawing instructions, and an image on that page is one instruction: place this XObject inside this rectangle. The XObject is a stream of bytes plus a dictionary saying how wide it is, how tall, what colour space it uses and how it is compressed. The interesting part is the compression filter, because PDF has understood DCTDecode, which is baseline JPEG, since 1993. A JPEG therefore does not need converting to go in a PDF. Its existing compressed bytes are the stream, copied across untouched, and the same is true of PNG through FlateDecode. That is why nothing here re-encodes a JPEG or a PNG: the format already speaks both.',
      'What PDF has never understood is HEIC, and it is not going to. HEIC is HEVC video compression wearing an image container, patent-encumbered and roughly two decades newer than the filters PDF standardised. So an iPhone photograph has one honest path into a document: decode it, then encode it again as something the format knows. That happens here through libheif compiled to WebAssembly, followed by a canvas encode to JPEG at quality 0.92. It is a genuine lossy step, the only one in this tool, which is why the interface names each file it happened to rather than presenting a conversion as a copy. WebP and AVIF take the same route for the same reason.',
      'Geometry is where an image-to-PDF tool usually gets careless. A page is measured in points, at 72 to the inch, and a photograph is measured in pixels, which are not a physical unit at all. There is no correct conversion between them, only a choice of DPI, and picking one badly produces the classic failure: a 4000 pixel wide photo declared at 72 DPI becomes a page 55 inches across, valid PDF that no printer will touch. This tool sidesteps the question by never deriving the page from the pixel count. On A4 or Letter the page is that paper, and the image is scaled to fit inside a 36 point margin. In borderless mode the page takes the image aspect ratio and is sized so its long edge equals A4 long edge, which keeps a borderless page a printable page.',
      'Orientation is decided per image rather than per document. Each page carries its own MediaBox, so a landscape photograph gets a landscape page in the same file as a portrait one, and neither is rotated or letterboxed to match the other. This is worth stating because the alternative that most converters ship, one fixed orientation for the whole document, is what puts a photographed receipt sideways and small in the middle of a portrait sheet. The cost is that a merged document may alternate orientation, which readers handle without comment and printers offer to fit to the tray.',
      'None of this needs a server, and pdf-lib needs no WebAssembly either, so for a batch of JPEGs the whole job is byte copying and arithmetic. The constraint is memory rather than CPU: every image is held in the tab while the document is assembled, and the assembled document is held again as a blob before it is handed back. That is what limits a very large batch on a phone, and it is a fair trade for the property that matters, which is that a passport photograph, a bank card or a signed contract never leaves the device to have a wrapper put around it.',
    ],
  },

  'image-watermark': {
    heading: 'A watermark is a deterrent, and the honest version says so',
    paragraphs: [
      'Every tiled watermark makes exactly one promise that can be checked: that the mark is still there after somebody crops the picture. It is worth stating in those terms because the alternative claim, that a watermark protects an image, is not true and never has been. Anything drawn on top of pixels can be painted back out, and the tools for doing it went from specialist to one-click somewhere around 2023. What a mark actually buys is friction and provenance. Removing it is now a deliberate act rather than a right-click, and the copy that turns up somewhere else still says where it came from.',
      'So the tiling here is built around the crop, and the geometry falls out of that. Marks are laid on a lattice in their own rotated frame rather than stamped onto the image and turned afterwards, which is what keeps the spacing even when the angle is not zero. Alternate rows are offset half a step, because an aligned grid leaves clean vertical corridors between columns and a narrow crop can fall straight down one. And the lattice is sized so its cell diagonal never exceeds thirty percent of the shorter side of the image. That number is the promise: any point in the picture is then within half a cell of a mark, so any crop keeping thirty percent of the width and thirty percent of the height contains one.',
      'The consequence is that the mode overrules the size you asked for, and it is the only place in this tool that does. Ask for a mark half the height of the image and tile it, and no arrangement of it survives an aggressive crop, because the marks are too far apart to be dense and too big to be close. The engine solves for the largest mark that still satisfies the guarantee and uses that instead. A signature in the corner has no such constraint and gets exactly the size it was given.',
      'Sizing is relative to the image throughout, never in pixels. A mark is a fraction of the shorter side, and the margin is too. That is what makes one setting work across a batch where a 12 megapixel photograph sits next to a 600 pixel thumbnail, and it is also why the live preview can be trusted: the preview is the same code painting the same relative geometry onto a smaller copy, not an approximation of it. Text is measured by its ink rather than its font size for the same reason, since the em box of a line of lowercase and a line of capitals is identical and the visible height is not.',
      'Colour is chosen per mark from what is under it. A coarse luma map of the image is sampled beneath each placement, using the same weights the document scanner uses, and the mark goes dark on light ground and light on dark. This matters more than it sounds: a scan of an ID card is a bright sheet of paper with a dark photograph in the corner of it, and a single global choice of white or black is invisible over one half or the other. A halo in the opposite colour goes underneath, so the mark holds an edge either way.',
      'The one thing this tool cannot avoid is the re-encode. Painting means the pixels change, so unlike putting an image into a PDF there is no byte-for-byte path. JPEG comes back as JPEG at quality 0.92 and PNG comes back as PNG with its transparency, while HEIC, WebP and AVIF become JPEG because a canvas cannot write them back. A side effect worth knowing about is that the EXIF block does not survive, so the GPS coordinates and the camera serial number in the original are gone from the copy you hand out. That is usually what you wanted anyway.',
    ],
  },

  'pdf-merge': {
    heading: 'Why merging is the one PDF operation that loses nothing',
    paragraphs: [
      'A PDF is not a stream of pages, it is a graph of numbered objects. A page object holds a reference to a content stream, which is the list of drawing instructions, and to a resources dictionary naming the fonts and images that stream uses. Annotations, including links, hang off the page as their own objects. A separate page tree lists the pages in reading order. Nothing about where a page sits in the file is baked into the page itself, which is exactly why pages can be moved between documents at all.',
      'Merging, then, is copying. Each page object is copied into a new document along with everything it references, every internal reference is renumbered so two files that both used object 7 do not collide, and the copies are appended to the new page tree in the order you set. That is all this tool does. No image is decoded, no JPEG is re-encoded, no page is rasterised. The compressed bytes of a scan arrive in the merged file exactly as they left the original, which is why the text is still text afterwards and why a 300 DPI scan is still a 300 DPI scan. Compare that with compressing to a byte target, which has no choice but to re-render each page as a picture.',
      'Page geometry travels with the page too. Every page carries its own MediaBox measured in points, one point being 1/72 inch, so a merged document can legitimately hold an A4 scan, a US Letter payslip and a photographed receipt at their true sizes. Nothing is normalised to a single paper size. Readers display each page at its own dimensions; a printer will usually offer to scale them to whatever is in the tray, and that is a printing decision rather than something the file needs fixed in advance.',
      'What does not survive is everything that lives above the pages, in the document catalog. Bookmarks are an outline tree hanging off the catalog, not off any page, so they do not come along. Fill-in form fields are worse, because they half survive: the field definitions live in the document’s AcroForm, while the boxes you see are widget annotations attached to the page. Copy the pages and you get the widgets, showing whatever text was filled in, with no fields behind them. The merged copy therefore looks complete and is no longer fillable. That asymmetry is unusual enough to be worth a warning before the merge rather than a discovery afterwards, so the tool checks each file for form fields and says so up front.',
      'The output is a document created from scratch, which has a pleasant side effect. Its info dictionary starts empty, so no author, title, producing application or creation date comes across from any of the originals. Metadata sitting inside an embedded image is part of that image’s bytes and is untouched, so it is worth stripping separately when it matters. All of this runs on the main thread of your own browser tab. pdf-lib is plain JavaScript with no WebAssembly to fetch, so the only real constraint is memory: every file stays in the tab while its pages are copied, which is what limits a merge of hundreds of large scans on a modest phone.',
    ],
  },

  'screenshot-stitch': {
    heading: 'Finding the seam between two screenshots',
    paragraphs: [
      'Stitching a scroll capture is a search problem, and the thing being searched for is the amount the page moved between one screenshot and the next. Nobody scrolls by a fixed distance, so that number is different for every pair and cannot be assumed. It has to be measured, and the measurement has to be cheap enough to run on the phone the screenshots came from.',
      'The first step is to throw away almost everything. Each screenshot is squeezed horizontally to thirty-two brightness samples per row, so a picture that is millions of pixels becomes a few tens of thousands of numbers, one thin strip per row of the original. Two rows of a page that look the same have similar strips, and two rows that differ have different ones, which is the only property the search needs. The squeeze is done by the browser image scaler rather than by picking every nth column, because sampling columns would step straight over a one pixel line and call two different rows identical.',
      'Then every possible overlap is scored. For each candidate, a fixed sixty-four rows spread across the overlapping band are compared and the average difference is taken, so a candidate costs the same whether it claims twenty rows in common or two thousand. That fixed cost is what makes it affordable to try every offset instead of a sample of them, and trying every offset turns out to be necessary: a signature misaligned by two rows scores like unrelated content, not like a near miss, so there is no gradient to follow and nothing for a coarse pass to interpolate. The cheapest handful of candidates are then rescored against three times as many rows, which is what separates a real match from sixty-four rows that agreed by luck.',
      'The failure this design is most careful about is the confident wrong answer. A blank margin, an empty chat background or a run of white paper matches itself perfectly at every offset, so a matcher that only minimises difference will report a large overlap wherever the page is empty and silently delete the height in between. So a winning band is also asked whether its own rows differ from each other. A band with no vertical texture is not evidence, whatever it scores, and a pair that produces one is joined end to end and reported as unmatched rather than guessed at.',
      'The other thing that misleads a stitcher is the phone itself. The clock, the battery, the app toolbar and the tab bar do not scroll, so they are printed identically on every screenshot in the set, and those identical rows are exactly what a naive matcher reads as a perfect alignment. They are found first, by taking the number of leading rows that are unchanged across every consecutive pair and keeping the smallest, because that is the only part all of the screenshots agree on. One pair sharing more means the page repeated something there, not that the bar is taller. The result is capped at a quarter of the height, since two barely scrolled screenshots are identical over most of their area and without a ceiling the detector would conclude that almost everything is a status bar and merge the capture down to nothing.',
      'What comes out is a plan rather than a picture: a list of which rows of which screenshot land where. Painting it runs into a limit most people never meet, which is that a browser will not give you a canvas of unlimited size, and Safari in particular hands back a canvas of the size you asked for and then quietly draws nothing into it. So the limit is measured instead of looked up, by writing a pixel into the far corner and reading it back, and a capture too tall for this device is scaled to fit with the amount stated. The PDF is built a page at a time from the same plan, never allocating the full height at once, which is why it keeps every pixel of a capture the single image path has to shrink.',
    ],
  },

  'metadata-remove': {
    heading: 'What a photograph carries besides the photograph',
    paragraphs: [
      'Every photograph your phone takes carries a block of EXIF metadata, and its contents surprise most people. The GPS coordinates where the shutter fired, to a precision of a few metres. The exact date and time, to the second. The camera make, model and serial number. The lens. The software version. On many devices, a thumbnail of the original image, which survives even when the visible image has been cropped or edited.',
      'The serial number is the field people never think about, and it is the one that links photographs together. Two images posted to different places under different names, with no visible connection, share a camera serial and are therefore the same camera. Researchers and law enforcement both use exactly this. The GPS field is more obvious and no less consequential: a photograph of an item for sale, taken at home, publishes your home.',
      'Where this leaks is not usually social media. The large platforms strip EXIF on upload, which has trained people to assume it is handled. It is not handled anywhere else: email attachments keep it, messaging apps that send "as a document" keep it, marketplace listings on smaller sites keep it, and a file handed to someone on a USB stick obviously keeps it. The habit of assuming the platform will clean up is the risk.',
      'Stripping metadata is not the same as re-encoding. This tool rewrites the container and drops the metadata segments, leaving the compressed image data untouched, so the picture that comes out is bit-for-bit the picture that went in. Re-encoding would degrade the image slightly on every pass and would be the wrong tool for a job that is purely about what is attached to the file.',
      'One field is worth keeping deliberately: orientation. EXIF orientation tells a viewer to rotate the image, and removing it without applying the rotation first produces photographs that arrive sideways. That rotation is applied rather than discarded, which is the difference between a file that is clean and a file that is clean and still correct.',
    ],
  },

  'spreadsheet-compare': {
    heading: 'Why comparing two spreadsheets is harder than comparing two files',
    paragraphs: [
      'Diffing text is a solved problem: line by line, in order, and the answer is unambiguous. Spreadsheets defeat that immediately, because the row order carries no meaning. Export the same data twice from the same system and the rows may arrive in a different sequence, at which point a line-based diff reports that every row changed. It is technically correct and completely useless.',
      'So a spreadsheet comparison has to start by deciding what makes two rows the same row. That is the key column: an id, an SKU, an email address, an invoice number, whatever uniquely identifies a record in your data. Rows are matched on the key, then compared field by field. Choosing the key is the one decision the tool cannot make for you, and choosing it wrongly is the reason most comparisons produce nonsense. If the key is not unique, two different records collide and the differences reported between them are meaningless.',
      'The second trap is numeric equality. Spreadsheets store numbers as IEEE 754 doubles, and values that are equal in arithmetic are frequently not equal in bits. 0.1 plus 0.2 is not 0.3 in any language that uses doubles, including the one your spreadsheet application is written in. Compare two exported price lists with exact equality and you will find "differences" of one ten-billionth of a rupee scattered through them. A comparison that is useful for money needs a tolerance, and the tolerance needs to be visible so you know what it is treating as identical.',
      'Formatting is the third. A cell holding the number 1000 and a cell holding the text "1,000" look the same to a person and are not the same value. Dates are worse: a date is a number with a display format, and the same underlying day can appear as 08/20/2026, 20-08-2026 or 46,258 depending on locale and format. Comparing what is displayed rather than what is stored produces false differences; comparing what is stored without normalising produces the opposite.',
      'All of this runs in your browser, which for this tool is usually the point. The files that people most need to reconcile, bank statements against ledgers, supplier price lists, payroll exports, are exactly the files that should not be uploaded to a stranger to answer a question as small as "what changed".',
    ],
  },

  'passport-photo': {
    heading: 'Why passport photographs get rejected',
    paragraphs: [
      'Passport and visa photograph rejections are rarely about the photograph being bad. They are about measurements. Almost every authority specifies the head height as a proportion of the image, and that proportion is what an automated check measures first. The US requires the head to occupy between 50 and 69 percent of the frame height. The UK and the Schengen area measure the crown-to-chin distance in millimetres against a 45 mm tall print. India specifies a square photograph with its own ratios.',
      'This is why cropping a nice portrait to the right pixel dimensions fails. Getting a 2x2 inch image at 600x600 pixels satisfies the file specification and says nothing about where the head sits inside it. A photograph where the head is too small, which is the usual mistake because people frame like a normal portrait, is rejected by a system that never looked at the image quality at all.',
      'The second most common cause is the background. Requirements ask for plain white or off-white, evenly lit, with no shadow. A wall photographed with a flash produces a bright disc behind the head and darker corners, which is not an even background. A wall photographed without a flash usually produces a shadow on the side away from the window. Neither is a difficult problem to see once you know to look for it, and both are invisible to someone checking whether the picture looks nice.',
      'Then there are the rules that are simply lists: no smile showing teeth for most authorities, eyes open and clearly visible, no glasses for many countries now, head straight rather than tilted, mouth closed, no hair across the eyes, no uniform, plain everyday clothing, and no head covering except for religious reasons with the full face still visible. Each one is a separate reason a submission comes back weeks later.',
      'What this tool does is measure rather than guess. It works from the crop you place, computes the resulting head-height ratio against the specification you selected, and shows you the numbers you are being judged on before you submit. It cannot photograph you against a better wall, and it will not pretend that a rule about glasses is something software can fix.',
    ],
  },

  'document-scan': {
    heading: 'Scan quality decides OCR accuracy, and nothing downstream recovers it',
    paragraphs: [
      'Optical character recognition is often blamed for errors that were created before it ran. OCR works by isolating shapes and matching them against learned letterforms, so its accuracy is bounded by how cleanly the shapes can be isolated. If the characters are blurred, skewed, unevenly lit or fighting a patterned background, no amount of post-processing recovers information that the image never contained.',
      'The dominant factor is effective resolution on the text itself, not the megapixels of the camera. Roughly 300 dots per inch across the printed page is where accuracy stops improving much; well below 200, error rates climb sharply because the strokes that distinguish similar glyphs stop being resolved. This is why a 12 megapixel photograph taken at an angle from half a metre away often reads worse than a modest flatbed scan: the pixels exist but few of them are on the text.',
      'The second factor is contrast and evenness. A phone photograph of a page usually has a gradient across it, brighter near the window and darker at the far edge, plus the shadow of the phone itself. A global brightness threshold then either loses the pale text or fills the dark side with noise. The fix is adaptive thresholding, which computes a threshold for each neighbourhood of the image rather than one for the whole page, which is why the cleaning step here handles a lit-from-one-side photograph far better than a contrast slider does.',
      'Skew matters more than it appears to. A page rotated by three degrees still looks fine to a person, but line-finding algorithms segment text into rows, and a slope means a row crosses between lines of text. Deskewing before recognition is often the single largest accuracy gain available on phone-captured documents.',
      'A word on what a searchable PDF actually is, because it is widely misunderstood. It contains the page image exactly as before, plus a layer of invisible text positioned over the words. Your viewer draws the picture and searches the text. This means the recognition errors are still in the file, invisible, and a search for a word the OCR misread will not find it even though you can plainly see the word on screen. Searchable does not mean corrected.',
    ],
  },

  'mouse-test': {
    heading: 'What double-clicking by itself actually is',
    paragraphs: [
      'A mouse button is a mechanical switch, and mechanical switches bounce. When the contacts close they do not close once, cleanly. They make and break contact several times over a few milliseconds as the metal settles. Every mouse contains debounce logic, in firmware, that ignores further transitions for a short window after the first, which is what turns a messy physical event into one clean click.',
      'A worn switch bounces for longer than that window. The contacts oxidise, the spring weakens, and the settling time grows past the debounce period until a second transition arrives after the firmware has stopped ignoring them. The mouse then reports a second click that your finger never made. This is why the failure appears gradually, why it worsens over months, and why it happens to the left button first: it takes the most actuations.',
      'The measurable signature is the interval. A human double click has a gap between the two clicks in the range of roughly 80 to 500 milliseconds, bounded by how fast a finger can move. Switch chatter produces a second click within a few milliseconds of the first, usually under twenty, which no finger can do. That threshold is what separates a diagnosis from a guess, and it is what this tool measures: not whether a double click happened, but how long after the first click the second one arrived.',
      'The same timing view answers a different question people often have, which is whether the mouse is dropping clicks rather than adding them. A dropped click is a press with no release, or a release with no press, and it shows up in the raw event stream as an unmatched pair rather than as a short interval.',
      'Polling rate is a separate axis and worth not confusing with this. A 125 Hz mouse reports its position every 8 milliseconds and a 1000 Hz mouse every 1 millisecond, which affects how smooth the cursor feels and has nothing to do with whether the button chatters. A high polling rate on a worn switch is a fast report of a wrong click.',
    ],
  },

  'keyboard-test': {
    heading: 'Rollover, ghosting, and why your keyboard drops the third key',
    paragraphs: [
      'Keyboards do not have a wire per key. That would need over a hundred connections, so keys are wired as a grid of rows and columns and the controller scans it, energising one row at a time and reading which columns respond. A key at the intersection of row three and column five is identified by being the thing that connects them. This is efficient and it has a specific failure.',
      'Hold three keys that share rows and columns in the wrong arrangement, and the current finds a path through the other two that is indistinguishable from a fourth key being pressed. The controller reports a key nobody touched. That phantom is called ghosting, and the cheap defence against it is blocking: when the controller detects an ambiguous pattern it refuses to report the third key at all. Blocking is why a key you are definitely pressing does nothing, and it is far more common than ghosting because most manufacturers choose to drop input rather than invent it.',
      'The fix in hardware is a diode at every key, which makes current flow one way only and removes the phantom path. Keyboards advertising N-key rollover have those diodes. Keyboards advertising six-key rollover usually do not; six is the number of simultaneous keys the standard USB keyboard report can carry, and is a protocol limit rather than a matrix one. This is why the distinction matters to anyone gaming or playing a software instrument, and why it is invisible to anyone typing prose, where three simultaneous keys is already unusual.',
      'There is a second thing this tool tests that has nothing to do with rollover, which is layout. Browsers expose two different identifiers for a keystroke. One is the character produced, which depends on the layout, so the same physical key gives "a" on QWERTY and "q" on AZERTY. The other is the physical key position, which is the same everywhere. Testing has to track the physical position or the diagram lights up the wrong key for anyone not on a US layout, and where the browser can report your actual layout the printed legends are relabelled to match rather than showing you someone else keyboard.',
      'Keystrokes are read to drive the display and are never stored or transmitted, which is worth stating plainly on a page of this shape, since a keyboard tester is exactly what a keylogger would look like.',
    ],
  },

  ruler: {
    heading: 'Why an on-screen ruler has to be calibrated',
    paragraphs: [
      'A pixel is not a length. When CSS says an element is 96 pixels wide, that is a reference measurement defined against an assumed 96 pixels per inch, and almost no real display is 96 pixels per inch. A 24 inch 1080p monitor is about 92. A 27 inch 4K monitor is about 163. A modern phone is often above 400. Drawing a "one inch" line at 96 CSS pixels therefore produces a line that is one inch on nearly nothing.',
      'The browser cannot tell you the real number. It exposes the viewport in CSS pixels and a device pixel ratio, and neither carries the physical size of the panel. Screen dimensions in millimetres are not available to a web page, deliberately: the exact display geometry is a fingerprinting signal, and browsers have been closing those channels rather than opening them. So a page that claims to draw a real ruler without asking you anything is guessing, and the guess is wrong by up to 70 percent between common displays.',
      'The way out is to calibrate against an object whose size is fixed by international standard and which nearly everyone has. A bank card is exactly that. ISO/IEC 7810 ID-1 specifies 85.60 by 53.98 millimetres, and it governs every credit card, debit card and most national identity cards worldwide. You hold one against the screen, resize the outline until it matches, and that gives the one number the browser could not supply: how many pixels your display puts in a millimetre.',
      'From that single ratio everything else follows, and it is worth saving, because it is a property of the display rather than of the session. The calibration is stored on your device so the ruler is correct the next time you open it, and the value never leaves the browser, which matters given that it is precisely the kind of display fingerprint the platform declines to hand out.',
      'Two caveats, because they are the usual sources of error. Browser zoom changes the CSS pixel to physical pixel relationship, so a ruler calibrated at 100 percent zoom is wrong at 110 and you should recalibrate rather than compensate. And an external monitor is a different display: calibration follows the screen, not the computer.',
    ],
  },

  'camera-mic-test': {
    heading: 'The browser already knows why your camera is black',
    paragraphs: [
      'When a camera fails to start on a web page, the browser is not confused about the reason. The getUserMedia call rejects with a DOMException whose name is specified, and the name identifies the cause exactly. NotAllowedError means permission was refused, by you or by policy. NotFoundError means no device of that kind is attached. NotReadableError means the hardware is present and something else has it. OverconstrainedError means the device exists but cannot deliver the format that was asked for.',
      'Almost every webcam test page throws that away and shows a black rectangle. The information needed to fix the problem was returned by the platform and discarded by the page, which is why people end up reinstalling drivers to solve a conferencing app they left running in the background.',
      'That last case, NotReadableError, is the one worth knowing about, because it is both the most common and the least visible. On most systems a camera can be held by one application at a time. A video call that was closed with the window rather than quit, a recording tool minimised to the tray, or a background process that grabbed the device at login will hold it. Nothing on screen indicates this. The camera light may not even be on. The only symptom is that every other application reports a failure, and the reason is a program you believe you are not running.',
      'The microphone half has a different problem, which is that a still picture of a waveform proves nothing. The useful test is a level meter that moves with your voice, and the useful measurement is root mean square rather than peak: peak jumps on a single keystroke and reads as working, while RMS tracks sustained level, which is what tells you the microphone is genuinely picking up speech. A signal that registers but stays very low is a distinct diagnosis from silence, since one usually means input gain and the other usually means the wrong device is selected.',
      'It is also worth checking what the camera actually delivers rather than what was requested. A camera routinely ignores the resolution asked for and returns whatever it can, so the constraints tell you nothing; the track settings tell you the truth. That is the number to compare against a "1080p webcam" claim on a box. Nothing here is recorded: the stream is attached to a preview element and an audio analyser in the tab, and is discarded when you stop.',
    ],
  },

  'random-word': {
    heading: 'Randomness, bias, and why the size of the list is the whole answer',
    paragraphs: [
      'Most random word generators call Math.random. Browsers do not promise it is uniform, do not promise it is unpredictable, and are explicitly permitted to implement it with a fast generator whose output can be reconstructed from a handful of samples. For a party game that is fine. For anything you intend to use as a secret it is not, and the two uses sit on the same page in most tools without the difference being mentioned.',
      'Reaching for real cryptographic randomness is necessary and not sufficient, because the usual way of turning a random number into a list index reintroduces bias. Taking a 32-bit value modulo the list length is only uniform when the length divides 2^32 exactly, which for a list of 1,278 words it does not. The remainder means the first few hundred words come up very slightly more often than the rest, forever. The fix is rejection sampling: discard the values that fall in the incomplete final block and draw again. It costs an occasional extra draw, and it makes every word genuinely equally likely.',
      'That matters because the strength of a passphrase is arithmetic over the list, and the arithmetic is only true if the draw is fair. Each word contributes log2 of the list size in bits. Drawing from 1,278 words gives 10.32 bits per word, so eight words is 82.6 bits. Diceware, which draws from 7,776, gives 12.9 bits per word and reaches 77.5 bits in six. Eight words from a smaller curated list therefore beats six words from a larger one, which is the trade this list makes deliberately: every word is short, common and spellable from hearing, because a passphrase you cannot type is a passphrase you replace with something weak.',
      'Words are dealt rather than rolled. Each draw removes the word from the pool, so a list of twenty contains twenty different words and a game deals its whole deck before anything repeats. A passphrase cannot contain the same word twice either, which matters because repetition would make the real entropy lower than the number being displayed.',
      'One deliberate omission is worth explaining. Any draw here can be reproduced from a short code, so a class or a table of players can share one code and get identical words with no account and no server. The passphrase mode is structurally excluded from that: the function that generates it takes no seed parameter at all, so the sharing mechanism cannot reach it. A passphrase anyone holding a code can reproduce is not a secret, and the safest way to enforce that is to make it impossible to express rather than to remember not to do it.',
    ],
  },
  'font-coverage': {
    heading: 'The table inside a font that decides whether your text appears at all',
    paragraphs: [
      'Every font file carries a lookup table called the cmap, and it is the thing that answers the only question that matters here: given this character, which drawing does this font hold for it? A renderer consults it before anything else. If the answer is glyph zero, the font has nothing, and you get the empty rectangle that designers call tofu, or a substitute quietly pulled from some other font on the machine. This tool reads the same table the renderer reads, which is why its answer is not an estimate.',
      'The alternative approach, which most font checkers use, is to draw the character on a canvas in the font under test, draw it again in a fallback, and compare the pixels. It fails in three separate ways. Two fonts can draw a letter identically, so a real glyph looks like a miss. The browser substitutes a different font when one is missing, so a miss looks like a hit. And on a page with a font stack you are measuring whichever font actually won, not the one you asked about. A lookup is not a better guess than a measurement. It is a different kind of thing.',
      'Reading it correctly takes some care, because a cmap is several formats in one table and the useful ones are old. Format 4 covers the Basic Multilingual Plane through sorted segments, each mapping a range of characters either by adding a fixed delta or by pointing into a shared array of glyph ids, using a byte offset measured from the pointer\u2019s own position: an addressing trick from an era when the table was memory-mapped rather than parsed. Format 12 is the flat one that reaches past the BMP, where the emoji and the rarer scripts live. A font that has both carries the wider one as a superset, so that is the one to read.',
      'The trap in both is glyph zero. A segment can span a range of characters and still map some of them to nothing, and a reader that trusts the segment boundaries will report coverage the font does not have. That is a false positive on the exact question being asked, so every format here is evaluated down to the individual glyph id rather than to the range that contains it. Symbol fonts need naming too. Wingdings and its relatives hold no letters at all: they map the keyboard into a private-use block at U+F000 and draw a picture for each key, which makes them look like a perfect match for ordinary text. Where a font is doing that, the result says so.',
      'None of this needs the font file. A table directory sits in the first few hundred bytes and gives the offset and length of every table in the file, so the coverage of a twenty megabyte CJK font can be read with two short range requests against the file on disk. That is what makes scanning a few hundred installed fonts possible in a browser tab instead of an exercise in exhausting memory, and it is why nothing has to be uploaded: the bytes that answer the question are small, and they never have to leave the machine they are already on.',
      'One last thing is subtracted before any font is asked anything. Real text is full of characters that are never drawn: the zero-width joiners that hold an emoji family together, the variation selector that makes a heart red, the direction marks around an Arabic phrase, the byte-order mark an editor left at the front of the file. A font renders all of that correctly while owning a glyph for none of it. Counting them would report every font on the machine as failing, so they are filtered out first, and what remains is the set of characters a font is genuinely responsible for.',
    ],
  },
  'font-style': {
    heading: 'Ten numbers that try to describe what a typeface looks like',
    paragraphs: [
      'In 1985 a group at Elseware and later Hewlett-Packard set out to solve a problem that sounds trivial and is not: when a document asks for a font the machine does not have, what should it substitute? Answering that needs a way to describe what a typeface looks like in terms a program can compare. What they produced was PANOSE, ten numbers covering serif style, weight, proportion, contrast, stroke variation, arm style, letterform, midline and x-height. It is embedded in almost every font file shipped since, sitting in a table called OS/2, and it is the closest thing typography has to a machine-readable description of appearance.',
      'It is also, in practice, half empty. The ten digits are optional, every one of them has a value meaning "any", and a great many font files ship with all ten set to exactly that. Some were filled in by a conversion tool that never asked the designer. The result is a field that is genuinely informative when present and confidently wrong when trusted blindly, which is why this tool treats it as corroboration and never as the spine of an answer. All zeros is not read as a neutral font. It is read as nobody having said.',
      'The spine is the part of OS/2 that an operating system depends on, and therefore the part that is reliably correct. The weight class is a number from 100 to 900 that decides which file gets used when a document asks for bold. The width class from 1 to 9 does the same for condensed and extended. The family class separates oldstyle from transitional from Didone from slab from sans from script, using a scheme IBM published for its own typeface library. Get any of these wrong and the font misbehaves in every application on the machine, so they tend to be right.',
      'The most useful single number is one people rarely name. Every font from OS/2 version 2 onward records its x-height and its cap height, and the ratio between them is unitless, which means it compares directly across two fonts at any size. A ratio near 0.65 is a classical face with small lowercase letters and long extenders, which reads as formal and traditional and sets beautifully at large sizes. A ratio above 0.75 is a modern screen-oriented face whose lowercase nearly fills the cap height, which reads as friendly and plain and holds up at small sizes. That one fraction separates a wedding invitation from an app interface more reliably than any other field in the file.',
      'What none of it can do is tell you that a font is elegant. Elegance is not in the file. What is in the file is a high contrast between thick and thin strokes, a small x-height, a moderate weight and a serif of a particular shape, and the claim that this combination is what English speakers mean by elegant is a rubric somebody wrote down. This one is written down here, in the open, and every result on the page lists the traits that matched and the traits that did not, because the useful thing to hand someone is not a verdict but the reasoning behind it.',
      'The last constraint is honesty about absence. A font predating OS/2 version 2 has no recorded x-height, and one converted by a careless tool may have no recorded width. Scoring those as failures would rank a font by its age or by the software that produced it. So an untestable trait is dropped from the calculation rather than counted against the font, a score is matched over applicable, and a font that recorded nothing at all is set aside and labelled instead of being sorted to the bottom of a list it was never really in.',
    ],
  },
};
